# Generated by Django 3.2 on 2023-01-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('vacation', models.DateField(blank=True, null=True, verbose_name='Даты отпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('vacation', models.DateField(blank=True, null=True, verbose_name='Даты отпуска')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, unique=True, verbose_name='Заказчик')),
                ('time_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время заказа')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bucketorderapp.bouquet', verbose_name='Букет')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bucketorderapp.courier', verbose_name='Курьер')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bucketorderapp.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, unique=True, verbose_name='Заказчик')),
                ('time_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время формирования консультации')),
                ('time_finish', models.DateTimeField(verbose_name='Дата и время окончания консультации')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='bucketorderapp.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='Categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='bucketorderapp.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(related_name='bouquet_flowers', to='bucketorderapp.Flower', verbose_name='Цветы'),
        ),
    ]
