# Generated by Django 3.2 on 2023-01-19 12:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0003_auto_20230118_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='', max_length=128, region=None, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='bucketorderapp.specialist', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time_finish',
            field=models.DateTimeField(null=True, verbose_name='Дата и время окончания консультации'),
        ),
    ]
