# Generated by Django 3.2 on 2023-01-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0004_auto_20230119_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
    ]
