# Generated by Django 3.2 on 2023-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0005_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='customer',
            field=models.CharField(max_length=100, verbose_name='Заказчик'),
        ),
    ]
