# Generated by Django 3.2 on 2023-01-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0003_auto_20230119_0620'),
        ('bucketorderapp', '0006_alter_consultation_customer'),
    ]

    operations = [
    ]
