# Generated by Django 3.2 on 2023-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0008_flower_count_flower'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
