# Generated by Django 3.2 on 2023-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0009_auto_20230123_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
