# Generated by Django 3.2 on 2023-01-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='Categories',
            new_name='сategories',
        ),
    ]
