# Generated by Django 3.2 on 2023-01-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketorderapp', '0012_rename_categories_bouquet_сategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bouquet',
            old_name='сategories',
            new_name='categories',
        ),
    ]
